.\" SPDX-License-Identifier: CDDL-1.0
.\"
.\" This file and its contents are supplied under the terms of the
.\" Common Development and Distribution License ("CDDL"), version 1.0.
.\" You may only use this file in accordance with the terms of version
.\" 1.0 of the CDDL.
.\"
.\" A full copy of the text of the CDDL should have accompanied this
.\" source.  A copy of the CDDL is also available via the Internet at
.\" https://opensource.org/license/CDDL-1.0.
.\"
.\" Copyright (c) 2020 by Delphix. All rights reserved.
.\"
.Dd September 2, 2026
.Dt ZSTREAM 8
.Os
.
.Sh NAME
.Nm zstream
.Nd manipulate ZFS send streams
.Sh SYNOPSIS
.Nm
.Cm dump
.Op Fl Cvd
.Op Ar file
.Nm
.Cm decompress
.Op Fl v
.Oo Ar object Ns Sy \&, Ns Ar offset Ns Oo Sy \&, Ns Ar type Oc Ns … Oc
.Op Ar file
.Nm
.Cm drop_record
.Op Fl v
.Oo Ar object Ns Sy \&, Ns Ar offset Ns … Oc
.Op Ar file
.Nm
.Cm redup
.Op Fl v
.Ar file
.Nm
.Cm token
.Ar resume_token
.Nm
.Cm raw
.Op Fl v
.Op Fl b Ar max_buffers
.Op Fl g Ar from_guid
.Ar image|device
.Op Ar file
.Nm
.Cm recompress
.Op Fl t Ar num_threads
.Ar compress_type
.Op Ar file
.
.Sh DESCRIPTION
The
.Sy zstream
utility manipulates ZFS send streams output by the
.Sy zfs send
command.
.Pp
Apart from
.Cm token ,
which takes a resume token rather than a stream, every subcommand reads a send
stream either from the
.Ar file
named as its last argument or, when no file is given, from standard input.
.Cm redup
is the one subcommand that requires a
.Ar file :
it re-reads earlier parts of the stream to resolve deduplicated records, so it
cannot work on a pipe.
.Bl -tag -width ""
.It Xo
.Nm
.Cm dump
.Op Fl Cvd
.Op Ar file
.Xc
Print information about the specified send stream, including headers and
record counts.
The send stream may either be in the specified
.Ar file ,
or provided on standard input.
.Bl -tag -width "-D"
.It Fl C
Suppress the validation of checksums.
.It Fl v
Verbose.
Print metadata for each record.
.It Fl d
Dump data contained in each record.
Implies verbose.
.El
.Pp
The
.Nm zstreamdump
alias is provided for compatibility and is equivalent to running
.Nm
.Cm dump .
.It Xo
.Nm
.Cm token
.Ar resume_token
.Xc
Dumps zfs resume token information
.It Xo
.Nm
.Cm decompress
.Op Fl v
.Oo Ar object Ns Sy \&, Ns Ar offset Ns Oo Sy \&, Ns Ar type Oc Ns … Oc
.Op Ar file
.Xc
Decompress selected records in a ZFS send stream, read from the specified
.Ar file
or from standard input, when the compression type recorded in ZFS metadata may
be incorrect.
Specify the object number and byte offset of each record that you wish to
decompress.
Optionally specify the compression type.
The
.Ar type
can be any value accepted by the
.Sy compression
property, such as
.Sy off ,
.Sy gzip ,
.Sy lz4 ,
.Sy lzjb ,
.Sy zstd ,
or
.Sy zle .
A compression level, as in
.Sy gzip-3
or
.Sy zstd-5 ,
is accepted but ignored; only the algorithm matters when decompressing.
If no
.Ar type
is given, the compression type recorded in the record's own metadata is used.
Every record for that object beginning at that offset will be decompressed, if
possible.
It may not be possible, because the record may be corrupted in some but not
all of the stream's snapshots.
Specifying a compression type of
.Sy off
will change the stream's metadata accordingly, without attempting decompression.
This can be useful if the record is already uncompressed but the metadata
insists otherwise.
The repaired stream will be written to standard output.
.Bl -tag -width "-v"
.It Fl v
Verbose.
Print summary of decompressed records.
.El
.It Xo
.Nm
.Cm drop_record
.Op Fl v
.Oo Ar object Ns Sy \&, Ns Ar offset Ns … Oc
.Op Ar file
.Xc
Drop selected records, specified by object number and byte offset, from a ZFS
send stream read from the specified
.Ar file
or from standard input.
Only WRITE and WRITE_EMBEDDED records are supported, currently.
The repaired stream will be written to standard output.
.Bl -tag -width "-v"
.It Fl v
Verbose.
Print summary of dropped records.
.El
.It Xo
.Nm
.Cm redup
.Op Fl v
.Ar file
.Xc
Deduplicated send streams can be generated by using the
.Nm zfs Cm send Fl D
command.
The ability to send deduplicated send streams is deprecated.
In the future, the ability to receive a deduplicated send stream with
.Nm zfs Cm receive
will be removed.
However, deduplicated send streams can still be received by utilizing
.Nm zstream Cm redup .
.Pp
The
.Nm zstream Cm redup
command is provided a
.Ar file
containing a deduplicated send stream, and outputs an equivalent
non-deduplicated send stream on standard output.
Therefore, a deduplicated send stream can be received by running:
.Dl # Nm zstream Cm redup Pa DEDUP_STREAM_FILE | Nm zfs Cm receive No …
.Pp
A
.Ar file
is required here, rather than optional as it is for the other subcommands,
because resolving deduplicated records means re-reading earlier parts of the
stream.
.Bl -tag -width "-D"
.It Fl v
Verbose.
Print summary of converted records.
.El
.It Xo
.Nm
.Cm raw
.Op Fl v
.Op Fl b Ar max_buffers
.Op Fl g Ar from_guid
.Ar image|device
.Op Ar file
.Xc
Apply a zvol send stream, read from the specified
.Ar file
or from standard input, to a raw image or block device.
By default, at most 32
.Dv SPA_MAXBLOCKSIZE
buffers can be written at a time.
With
.Ar max_buffers
set to some value between 1 and
.Dv IOV_MAX ,
contiguous write records will be combined into one write operation using up to
this many buffers, at the cost of additional memory use.
When
.Ar from_guid
is provided, the initial from_guid of the stream will be checked to ensure it
matches the given value.
The final toguid of the stream is printed to stdout on completion.
With
.Fl v ,
details of the records in the stream are printed in similar fashion to
.Nm
.Cm dump .
.It Xo
.Nm
.Cm recompress
.Op Fl t Ar num_threads
.Ar compress_type
.Op Ar file
.Xc
Recompresses a send stream, read from the specified
.Ar file
or from standard input, using the specified compression
.Ar compress_type ,
and writes the modified stream to standard output.
All WRITE records in the send stream will be compressed unless compression
fails to reduce their size compared to being left uncompressed.
The
.Ar compress_type
can be any value accepted by the
.Sy compression
property, including one that names a compression level, such as
.Sy gzip-3 ,
.Sy zstd-5 ,
or
.Sy zstd-fast-1000 .
An
.Ar compress_type
of
.Sy off
decompresses every record and leaves the stream uncompressed.
Note that encrypted send streams cannot be recompressed.
.Bl -tag -width "-t"
.It Fl t Ar num_threads
Specifies the number of compression worker threads.
By default,
.Nm zstream Cm recompress
creates a thread for every CPU core.
It's generally unproductive to raise
.Ar num_threads
above this default.
On some architectures, contention for resources such as memory caches can
reduce efficiency when many threads are active.
On those systems, it may be helpful to run with fewer threads,
particularly when automating operations on shared servers.
.It Fl l Ar level
Deprecated.
Specifies a
.Sy zstd
compression level, and may be used only with a
.Ar compress_type
of
.Sy zstd .
Give the level as part of the
.Ar compress_type
instead, as in
.Sy zstd-5 .
.El
.El
.
.Sh EXAMPLES
.Ss Recovering from OpenZFS bug #12762
First, determine which records are corrupt.
That cannot be done automatically; it requires information beyond ZFS's
metadata.
If object
.Sy 128
is corrupted at offset
.Sy 0
and is compressed using
.Sy lz4 ,
then run this command:
.Bd -literal
.No # Nm zfs Ar send Fl c Ar … | Nm zstream decompress Ar 128,0,lz4 | \
Nm zfs recv Ar …
.Ed
.
.Ss Recovering from OpenZFS bug #18239
The bogus records typically have an absurdly large offset, and can be seen with
a command like
.Nm zdb Fl ddddd Ar dataset Ar object
or
.Nm zstream Ar dump Fl v .
To recover, send the dataset and use
.Nm zstream
to drop the bogus record, then receive into a new dataset.
.Bd -literal
.No # Nm zfs Ar send Ar ... | Nm zstream drop_record Ar 3545761,18446744073709486080 | \
Nm zfs recv Ar ...
.Ed
.
.Ss Migrating from a zvol to a physical disk
Given a zvol tank/vol with snapshots @1 @2 and @3, and an adequately sized
physical disk /dev/sdd:
.Bd -literal
.No # Nm zfs Cm send Fl Lec Ar tank | Nm zstream Cm raw Ar /dev/sdd
16731506615198184313
.No # Nm zfs Cm send Fl Lec Fl I Ar @1 Ar tank/vol@3 | Nm zstream Cm raw Fl g Ar 16731506615198184313 Ar /dev/sdd
10690368765373298656
.Ed
.Sh SEE ALSO
.Xr zdb 8 ,
.Xr zfs 8 ,
.Xr zfs-receive 8 ,
.Xr zfs-send 8 ,
.Lk https://github.com/openzfs/zfs/issues/12762
.Lk https://github.com/openzfs/zfs/issues/18239
